### ISSUE TITLE
output -nan

### ISSUE THREAD

**Issue by lorenapinilla98** [haplotype/elai#8]
Hello,

I'm using this command:

 ./elai-lin -g chr1dogs.recode.geno.txt -p 10 -g chr1wolves.recode.geno.txt -p 11 -g chr1admixed.recode.geno.txt -p 1 -pos positionchr1_file.txt -s 30 -o output_chr1 -C 2 -c 10 -mg 10

And my outputs appear with  " -nan " as result.
This chr1 has  898121 SNPs and 81 individuals in total. Therefore, what could be the problem?

**Comment by haplotype** [comment]
it’s caused by underflow. i thought i fixed it, but apparently not.

can i see the log?

**Comment by lorenapinilla98** [comment]
Hello,

I was trying with this command:

 ./elai-lin -g pop1.recode.geno.txt -p 10 -g pop2.recode.geno.txt -p 11 -g admixed.recode.geno.txt -p 1 -pos position_file.txt -s 20 -o output_ -C 2 -c 10 -mg 5

And, at the moment, I was able to obtain the correct outputs for some chromosomes, but for others, as the chromosome 2 as an example, I'm obtaining this log:

Running ELAI for CHR2
## randseed = 1751989861
-warning: number of position files = 1
-warning: position files contain 624732 records.
-warning: file 0 has 18 individual and 624732 snps
-warning: file 1 has 18 individual and 624732 snps
-warning: file 2 has 8 individual and 624732 snps
number of individuals = 44
number of SNPs = 624732
### m_morgan = 0.854255
-warning: read file 0 again
-warning: read file 1 again
-warning: read file 2 again
-warning: total number of individuals = 44
11.1111 11.1111 11.1111 11.1111 11.1111 11.1111 11.1111 11.1111 11.1111 11.1111 11.1111 11.1111 11.1111 11.1111 11.1111 11.1111 11.1111 11.1111 11.1111 11.1111 11.1111 11.1111 11.1111 11.1111 11.1111 11.1111 11.1111 11.1111 11.1111 11.1111 11.1111 11.1111 11.1111 11.1111 11.1111 11.1111 1 1 1 1 1 1 1 1
nPanel = 36 ## nCohort = 8
 ### Exact update 0 0    -15246203.228  -15246203.228
 ### Exact update 0 1    -5091300.014   10154903.214
 ### Exact update 0 2    -2507205.317   2584094.697
 ### Exact update 0 3        -nan           -nan
### Exact update 0 4        -nan           -nan
 ### Exact update 0 5        -nan           -nan
 ### Exact update 0 6        -nan           -nan
 ### Exact update 0 7        -nan           -nan
 ### Exact update 0 8        -nan           -nan
 ### Exact update 0 9        -nan           -nan
 ### Exact update 0 10       -nan           -nan
 ### Exact update 0 11       -nan           -nan
 ### Exact update 0 12       -nan           -nan
 ### Exact update 0 13       -nan           -nan
 ### Exact update 0 14       -nan           -nan
 ### Exact update 0 15       -nan           -nan
 ### Exact update 0 16       -nan           -nan
 ### Exact update 0 17       -nan           -nan
 ### Exact update 0 18       -nan           -nan
 ### Exact update 0 19       -nan           -nan

**Comment by haplotype** [comment]
in the command line add -w 10 and try again.
this invokes linear approximation to fit the EM to warm up, and then fit
the EM with quadratic algorithm. in another thread for a nonhuman subjects,
this works.

**Comment by lorenapinilla98** [comment]
Hello,
I tried and still appear this problem:

## randseed = 1752049708
-warning: number of position files = 1
-warning: position files contain 898121 records.
-warning: file 0 has 20 individual and 898121 snps
-warning: file 1 has 20 individual and 898121 snps
-warning: file 2 has 15 individual and 898121 snps
number of individuals = 55
number of SNPs = 898121
### m_morgan = 1.22668
-warning: read file 0 again
-warning: read file 1 again
-warning: read file 2 again
-warning: total number of individuals = 55
18.75 18.75 18.75 18.75 18.75 18.75 18.75 18.75 18.75 18.75 18.75 18.75 18.75 18.75 18.75 18.75 18.75 18.75 18.75 18.75 18.75 18.75 18.75 18.75 18.75 18.75 18.75 18.75 18.75 18.75 18.75 18.75 18.75 18.75 18.75 18.75 18.75 18.75 18.75 18.75 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
nPanel = 40 ## nCohort = 15
 ### Approximate update0 0       -29240709.403  -29240709.403
 ### Approximate update0 1       -11963384.373  17277325.030
 ### Approximate update0 2       -6293367.104   5670017.269
 ### Approximate update0 3       -5493721.083   799646.020
 ### Approximate update0 4       -5370984.577   122736.506
 ### Approximate update0 5       -5334104.786   36879.791
 ### Approximate update0 6       -5323590.621   10514.165
 ### Approximate update0 7       -5320650.147   2940.474
 ### Approximate update0 8       -5319378.841   1271.306
 ### Approximate update0 9       -5319855.583   -476.741
 ### Exact update 0 0    -3470590.351   -3470590.351
 ### Exact update 0 1        -nan           -nan

**Comment by haplotype** [comment]
is it possible for you to share the data with me?
if not, try to split the SNPs into two overlapping sets and run them
separately.
you can do it by split the positions only and use —exclude-nopos

**Comment by lorenapinilla98** [comment]
What exactly does that flag do?

**Comment by haplotype** [comment]
exclude snps that have no position

**Comment by lorenapinilla98** [comment]
Genetic position (cM) or physical position (bp)?

**Comment by haplotype** [comment]
suppose you have a position file with 3 SNPs

rs1 100 22
rs2 200 22
rs3 300 22

suppose you only want rs1 and rs3 then you delete the second row from the
position file, use —exclude-nopos. ELAI will ignore rs2.
